# Generated by Django 6.0.6 on 2026-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesvariant',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='shoes',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/thumbnails/'),
        ),
    ]
