# Generated by Django 6.0.6 on 2026-07-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_views', to='shoes.shoes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['shoe', 'created_at'], name='shoes_shoev_shoe_id_ac1bee_idx'), models.Index(fields=['user', 'created_at'], name='shoes_shoev_user_id_d21f49_idx'), models.Index(fields=['visitor_id', 'created_at'], name='shoes_shoev_visitor_fe2dc0_idx')],
            },
        ),
    ]
