# Generated by Django 6.0.6 on 2026-07-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_shoes_options_reviewmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
