# Generated by Django 6.0.6 on 2026-07-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_brand_id_alter_category_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='customizer_id',
            field=models.CharField(blank=True, choices=[('nike-converse-low-top', 'Converse Low Top'), ('nike-converse-high-top', 'Converse High Top'), ('air-runner', 'Air Runner'), ('air-jordan-1', 'Air Jordan 1'), ('low-poly-boot', 'Low Poly Boot'), ('urban-canvas', 'Urban Canvas')], help_text='Which 3D customizer model this catalog shoe should open.', max_length=64, null=True),
        ),
    ]
