# Generated by Django 6.0.6 on 2026-07-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_shoeview'),
        ('shoes', '0006_reviewreply'),
    ]

    operations = [
    ]
