# Generated by Django 6.0.6 on 2026-07-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0007_merge_0004_shoeview_0006_reviewreply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
