# Generated by Django 6.0.6 on 2026-07-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_shoes_customizer_id'),
        ('shoes', '0008_alter_order_status'),
    ]

    operations = [
    ]
