# Generated by Django 6.0.6 on 2026-08-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_shoes_customizer_id'),
        ('shoes', '0008_alter_order_status'),
    ]

    operations = [
    ]
