# Generated by Django 6.0.6 on 2026-07-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
    ]
