# Generated by Django 6.0.6 on 2026-08-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_orderitem_colors_orderitem_pattern_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/'),
        ),
    ]
