# Generated by Django 6.0.6 on 2026-08-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0009_merge_20260802_1317"),
        ("shoes", "0011_orderitem_photo"),
    ]

    operations = []
