# Generated by Django 6.0.6 on 2026-08-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ("shoes", "0002_seed_initial_shoe_data"),
    ("shoes", "0009_merge_20260802_1317"),
]

    operations = []
