# Generated by Django 6.0.6 on 2026-08-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcastmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('delivery', 'Delivery'), ('admin', 'Admin Broadcast'), ('general', 'General'), ('failed', 'Failed')], default='general', max_length=20),
        ),
    ]
