# Generated by Django 6.0.6 on 2026-08-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("shoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shoes.shoesvariant",
            ),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pattern__isnull", False),
                    ("variant__isnull", False),
                    _connector="OR",
                ),
                name="cartitem_has_pattern_or_variant",
            ),
        ),
    ]
