
# Generated by Django 4.2.30 on 2026-07-11 17:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('account', '0004_address'),
        ('account', '0004_cartitem'),
    ]

    operations = [
    ]

