# Generated by Django 6.0.6 on 2026-07-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_address"),
        ("account", "0004_cartitem"),
    ]

    operations = []
