# Generated by Django 6.0.6 on 2026-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_merge_0004_address_0004_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
