# Generated by Django 6.0.6 on 2026-07-13 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_0004_address_0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pattern',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=8),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
