# Generated by Django 6.0.6 on 2026-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_address_created_at_remove_cartitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cart_photos/'),
        ),
    ]
