# Generated by Django 6.0.6 on 2026-07-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_address_created_at_alter_address_city_and_more'),
        ('account', '0007_cartitem_photo'),
    ]

    operations = [
    ]
