# Generated by Django 6.0.6 on 2026-07-18 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_address_city_alter_address_district_and_more'),
        ('shoes', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shoes.shoesvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pattern',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(('pattern__isnull', False), ('variant__isnull', False), _connector='OR'), name='cartitem_has_pattern_or_variant'),
        ),
    ]
