# Generated by Django 6.0.6 on 2026-08-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('account', '0002_initial'),
    ('shoes', '0009_merge_20260728_0858'),
]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_cart_items', to='shoes.order'),
        ),
    ]
