# Generated by Django 6.0.6 on 2026-08-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_address_id_alter_cartitem_id_and_more'),
        ('shoes', '0009_merge_20260728_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_cart_items', to='shoes.order'),
        ),
    ]
