# Generated by Django 6.0.6 on 2026-08-02 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 2, 5, 53, 15, 926367, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
