# Generated by Django 6.0.6 on 2026-08-02 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('account', '0002_initial'),
    ('shoes', '0001_initial'),
]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.CharField(blank=True, max_length=8, null=True)),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='shoes.shoesvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('pattern__isnull', False), ('variant__isnull', False), _connector='OR'), name='wishlistitem_has_pattern_or_variant'), models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('user', 'variant'), name='unique_wishlist_variant_per_user')],
            },
        ),
    ]
